version: "3"

services:
    client:
        image: nginx
        ports:
            - 8001:80
        volumes:
            - //wsl.localhost/docker-desktop-data/data/docker/volumes/portainer_data/_data/compose/11/src:/usr/share/nginx/html
